dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n taxcalc-dev python=$TRAVIS_PYTHON_VERSION;
  - source activate taxcalc-dev
  # - conda env update -f environment.yml
  - pip install pyyaml
  # Changed the code to take care of the pep8 test failure
  # - pip install pytest-pep8
  - pip install pytest-pycodestyle
  - pip install coverage
  - pip install codecov
  - python setup.py install


# command to run tests
script:
  # Changed the code to take care of the pep8 test failure
  # - python -c "import taxcalc"; coverage run -m pytest -v -m "not local" --pep8
  - python -c "import taxcalc"; coverage run -m pytest -v -m "not local" --pycodestyle

after_success:
  - codecov
